export const Images = {
  bg: require("../assets/images/bg.jpeg"),
};

export const transactions = [
  {
    id: "txn_001",
    description: "Wallet funded via bank transfer",
    amount: "¥20.00",
    status: "successful",
    direction: "incoming",
    type: "wallet fund",
  },
  {
    id: "txn_002",
    description: "Purchased RMB at ¥140.00 rate",
    amount: "¥140.00",
    status: "completed",
    direction: "outgoing",
    type: "rmb purchase",
  },
  {
    id: "txn_003",
    description: "Electricity bill payment",
    amount: "¥35.00",
    status: "successful",
    direction: "outgoing",
    type: "bill payment",
  },
  {
    id: "txn_004",
    description: "Withdrawal to bank account",
    amount: "¥200.00",
    status: "pending",
    direction: "outgoing",
    type: "withdrawal",
  },
  {
    id: "txn_005",
    description: "Wallet funded via USSD",
    amount: "¥50.00",
    status: "completed",
    direction: "incoming",
    type: "wallet fund",
  },
  {
    id: "txn_006",
    description: "Purchased RMB at low rate",
    amount: "¥100.00",
    status: "successful",
    direction: "outgoing",
    type: "rmb purchase",
  },
  {
    id: "txn_007",
    description: "Airtime top-up (MTN)",
    amount: "¥15.00",
    status: "completed",
    direction: "outgoing",
    type: "bill payment",
  },
  {
    id: "txn_008",
    description: "Received refund for failed transaction",
    amount: "¥30.00",
    status: "successful",
    direction: "incoming",
    type: "wallet fund",
  },
  {
    id: "txn_009",
    description: "Withdrew to Opay",
    amount: "¥75.00",
    status: "completed",
    direction: "outgoing",
    type: "withdrawal",
  },
  {
    id: "txn_010",
    description: "Utility bill payment",
    amount: "¥60.00",
    status: "pending",
    direction: "outgoing",
    type: "bill payment",
  },
];
